### ISSUE TITLE
Неверная аватарка у админа при ответе

### ISSUE THREAD

**Issue by ivyanni** [vertvvv/TicketSaleSystem#11]
![image](https://cloud.githubusercontent.com/assets/8677685/22461305/c5209f32-e7b9-11e6-9db6-9e0dddb715f9.png)
У админа в данном случае другая аватарка, в ответе отображается пользовательская.
(После закрытия и повторного открытия окна диалога всё становится норм)

**Comment by vertvvv** [comment]
Исправлено
