### ISSUE TITLE
Есть возможность заказа билетов на прошедшую дату

### ISSUE THREAD

**Issue by ivyanni** [vertvvv/TicketSaleSystem#12]
Через всплывающий календарь это не сделать, а вот кнопочками или вводя число и месяц с клавиатуры это возможно. Проблема тут даже не в том, что такую дату можно установить (сомневаюсь, что будет верным полностью запретить ввод с клавиатуры). Думаю, нужно просто самому делать проверку даты.
![image](https://cloud.githubusercontent.com/assets/8677685/22860983/57e2c1de-f11e-11e6-8265-78f70eb4a640.png)

**Comment by vertvvv** [comment]
Исправил - если дата не входит в нужный интервал, то поле ввода подсвечивается и кнопка "купить" недоступна для нажатия.
