### ISSUE TITLE
При регистрации не обрабатывается ошибка с уже зарегистрированным email

### ISSUE THREAD

**Issue by ivyanni** [vertvvv/TicketSaleSystem#2]
В бэке я пофиксил,  будет выдавать 400 ошибку с сообщением E-mail already in use

**Comment by vertvvv** [comment]
Можешь переделать выдаваемую ошибку? Чтобы атрибутом описания ошибки было не desc, а error_description, как стандартное? Так будет удобнее обрабатывать, да и так, наверное, правильнее.
![image](https://cloud.githubusercontent.com/assets/8975038/22071466/4e785e46-ddb0-11e6-8a14-5318fe0e924b.png)

**Comment by vertvvv** [comment]
Сделал временную обработку так, как в бэке сейчас, но лучше переделать, если возможно

**Comment by ivyanni** [comment]
Переделаю в следующем коммите

**Comment by vertvvv** [comment]
Окей, тогда закрываю
