### ISSUE TITLE
После сохранения настроек страница не обновляется

### ISSUE THREAD

**Issue by ivyanni** [vertvvv/TicketSaleSystem#3]
Также надо убрать отсюда текст, если поля не заполнены
![image](https://cloud.githubusercontent.com/assets/8677685/22058279/749fe9d6-dd79-11e6-86b1-263f27ce03c5.png)

**Comment by vertvvv** [comment]
Уже пофиксил обновление страницы, но коммит еще не заливал. С полями сделано так, что если пустое одное из полей имя/фамилия, то будет Name Surname выводиться, соответственно с birth date также - если там пусто, то ХХ.ХХ.ХХХХ будет.

**Comment by ivyanni** [comment]
Это я понял, просто имхо некрасиво выглядят вот эти кресты и Name Surname

**Comment by vertvvv** [comment]
Окей, посмотрю, может быть есть смысл их убрать
