### ISSUE TITLE
В качестве UUID категории отправляется undefined 

### ISSUE THREAD

**Issue by ivyanni** [vertvvv/TicketSaleSystem#4]
Когда редактируешь аттракционы в админ панели можно сделать так:

1. В New Attraction создаёшь новую категорию.
2. Переходишь на редактирование существующего аттракциона.
3. Выставляешь ему созданную категорию.
4. При нажатии Change в качестве UUID отправится undefined, что вызовет 500 ошибку.

**Comment by vertvvv** [comment]
Пофиксил
